'use strict';

exports.BattlePokedex = {


	infernape: {
		num: 392,
		species: "Infernape",
		types: ["Fire", "Fighting"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 64, atk: 104, def: 71, spa: 104, spd: 71, spe: 108},
		abilities: {0: "Hero Pride"},
		heightm: 1.2,
		weightkg: 55,	
		forme: "Mega",
		formeLetter: "M",
		color: "Brown",
		prevo: "monferno",
		evoLevel: 36,
		eggGroups: ["Field", "Human-Like"],
	},
	pikachuphd: {
		species: "Pikachu-PhD",
		types: ["Electric"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 35, atk: 155, def: 40, spa: 150, spd: 50, spe: 90}, //o atk é o msm com o boost de light ball
		abilities: {0: "Reckless"},
		heightm: 1.2,
		weightkg: 55,	
		forme: "Mega",
		formeLetter: "M",
		color: "Yellow",
		prevo: "pikachu",
		evoLevel: 36,
		eggGroups: ["Field", "Fairy"],
	},
	greninjaash: {
		species: "Greninja-Ash",
		types: ["Water","Dark"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 90, atk: 95, def: 94, spa: 130, spd: 105, spe: 96}, //o atk é o msm com o boost de light ball
		abilities: {0: "Protean"},
		heightm: 1.2,
		weightkg: 55,	
		forme: "Mega",
		formeLetter: "M",
		color: "Blue",
		prevo: "poliwrath",
		evoLevel: 36,
		eggGroups: ["Field", "Lixo"],
	},
		empoleon: {
		num: 395,
		species: "Empoleon",
		types: ["Water", "Steel", "Flying"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 84, atk: 86, def: 88, spa: 111, spd: 101, spe: 60},
		abilities: {0: "Serene Grace"},
		heightm: 1.7,
		weightkg: 84.5,
		color: "Blue",
		prevo: "prinplup",
		evoLevel: 36,
		eggGroups: ["Water 1", "Field"],
	},
	cofagrigus: {
		num: 563,
		species: "Cofagrigus",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 58, atk: 50, def: 145, spa: 95, spd: 105, spe: 30},
		abilities: {0: "baixarhentai.net"},
		heightm: 1.7,
		weightkg: 76.5,
		color: "Yellow",
		prevo: "yamask",
		evoLevel: 34,
		eggGroups: ["Mineral", "Amorphous"],
	},
	lilligant: {
		num: 549,
		species: "Lilligant",
		types: ["Grass", "Fairy"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 70, atk: 60, def: 75, spa: 110, spd: 75, spe: 90},
		abilities: {0: "Sheer Force"},
		heightm: 1.1,
		weightkg: 16.3,
		color: "Green",
		prevo: "petilil",
		evoLevel: 1,
		eggGroups: ["Grass"],
	},
	wobbuffet: {
		num: 202,
		species: "Wobbuffet",
		types: ["Psychic", "Ghost"],
		baseStats: {hp: 190, atk: 33, def: 58, spa: 33, spd: 58, spe: 33},
		abilities: {0: "Shadow Tag"},
		heightm: 1.3,
		weightkg: 28.5,
		color: "Blue",
		prevo: "wynaut",
		evoLevel: 15,
		eggGroups: ["Amorphous"],
	},
		raikou: {
		num: 243,
		species: "Raikou",
		types: ["Electric", "Fire", "Flying"],
		gender: "N",
		baseStats: {hp: 90, atk: 85, def: 75, spa: 115, spd: 100, spe: 115},
		abilities: {0: "Useless"},
		heightm: 1.9,
		weightkg: 178,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	garchomp: {
		num: 445,
		species: "Garchomp",
		types: ["Dragon", "Steel"],
		baseStats: {hp: 108, atk: 130, def: 95, spa: 80, spd: 85, spe: 102},
		abilities: {0: "Arena Trap"},
		heightm: 1.9,
		weightkg: 95,
		color: "Blue",
		prevo: "gabite",
		evoLevel: 48,
		eggGroups: ["Monster", "Dragon"],
		otherFormes: ["garchompmega"],
	},
		garchompmega: {
		num: 445,
		species: "Garchomp-Mega",
		baseSpecies: "Garchomp",
		forme: "Mega",
		formeLetter: "M",
		types: ["Dragon", "Steel"],
		baseStats: {hp: 108, atk: 170, def: 115, spa: 120, spd: 95, spe: 92},
		abilities: {0: "Arena Trap"},
		heightm: 1.9,
		weightkg: 95,
		color: "Blue",
		eggGroups: ["Monster", "Dragon"],
	},
		vivillon: {
		num: 666,
		species: "Vivillon",
		types: ["Bug", "Fairy"],
		baseStats: {hp: 80, atk: 52, def: 50, spa: 90, spd: 50, spe: 89},
		abilities: {0: "Magic Guard"},
		heightm: 1.2,
		weightkg: 17,
		color: "Black",
		prevo: "spewpa",
		evoLevel: 12,
		eggGroups: ["Bug"],
		otherForms: ["vivillonarchipelago", "vivilloncontinental", "vivillonelegant", "vivillongarden", "vivillonhighplains", "vivillonicysnow", "vivillonjungle", "vivillonmarine", "vivillonmodern", "vivillonmonsoon", "vivillonocean", "vivillonpolar", "vivillonriver", "vivillonsandstorm", "vivillonsavanna", "vivillonsun", "vivillontundra"],
		otherFormes: ["vivillonfancy", "vivillonpokeball"],
	},
		mankey: {
		num: 56,
		species: "Mankey",
		types: ["Fighting", "Ghost"],
		baseStats: {hp: 40, atk: 80, def: 35, spa: 35, spd: 45, spe: 70},
		abilities: {0: "Opa Fion"},
		heightm: 0.5,
		weightkg: 28,
		color: "Brown",
		evos: ["primeape"],
		eggGroups: ["Field"],
	},
		corphish: {
		num: 341,
		species: "Corphish",
		types: ["Water", "Dark"],
		baseStats: {hp: 43, atk: 80, def: 65, spa: 50, spd: 35, spe: 35},
		abilities: {0: "Hyper Cutter", 1: "Shell Armor", H: "Adaptability"},
		heightm: 0.6,
		weightkg: 11.5,
		color: "Red",
		evos: ["crawdaunt"],
		eggGroups: ["Water 1", "Water 3"],
	},
	jirachi: {
		num: 385,
		species: "Jirachi",
		types: ["Steel", "Fire"],
		gender: "N",
		baseStats: {hp: 100, atk: 100, def: 100, spa: 100, spd: 100, spe: 100},
		abilities: {0: "Regenerator"},
		heightm: 0.3,
		weightkg: 1.1,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	bewear: {
		num: 760,
		species: "Bewear",
		types: ["Normal", "Ghost"],
		baseStats: {hp: 120, atk: 125, def: 80, spa: 55, spd: 60, spe: 60},
		abilities: {0: "Fluffy", 1: "Klutz", H: "Unnerve"},
		heightm: 2.1,
		weightkg: 135,
		color: "Pink",
		prevo: "stufful",
		evoLevel: 27,
		eggGroups: ["Field"],
	},
		furret: {
		num: 162,
		species: "Furret",
		types: ["Normal", "Bird"],
		baseStats: {hp: 85, atk: 76, def: 64, spa: 45, spd: 55, spe: 90},
		abilities: {0: "Run Away", 1: "Keen Eye", H: "Frisk"},
		heightm: 1.8,
		weightkg: 32.5,
		color: "Brown",
		prevo: "sentret",
		evoLevel: 15,
		eggGroups: ["Field"],
	},
	
};